//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IMartinezAereomexicoEntities : DbContext
    {
        public IMartinezAereomexicoEntities()
            : base("name=IMartinezAereomexicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vuelo> Vuelos { get; set; }
        public virtual DbSet<Reservacione> Reservaciones { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual ObjectResult<BusquedaVuelos_Result> BusquedaVuelos(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaVuelos_Result>("BusquedaVuelos", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual int AddReservacion(Nullable<int> idUsuario, Nullable<int> idVuelo)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idVueloParameter = idVuelo.HasValue ?
                new ObjectParameter("IdVuelo", idVuelo) :
                new ObjectParameter("IdVuelo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddReservacion", idUsuarioParameter, idVueloParameter);
        }
    
        public virtual ObjectResult<GetAllVuelos_Result> GetAllVuelos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllVuelos_Result>("GetAllVuelos");
        }
    
        public virtual ObjectResult<GetDestino_Result> GetDestino(string destino)
        {
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDestino_Result>("GetDestino", destinoParameter);
        }
    
        public virtual ObjectResult<LisGVuelos_Result> LisGVuelos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LisGVuelos_Result>("LisGVuelos");
        }
    
        public virtual ObjectResult<UsuariosGetall_Result> UsuariosGetall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuariosGetall_Result>("UsuariosGetall");
        }
    }
}
